services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [fakenews-net]

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
    networks: [fakenews-net]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: fakenews-maroc
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on: [kafka]
    networks: [fakenews-net]

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks: [fakenews-net]

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/fakenews-lake --ignore-existing;
      mc anonymous set public local/fakenews-lake;
      echo 'Bucket fakenews-lake cree';
      "
    networks: [fakenews-net]

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: fakenews_dw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fakenews_dw"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [fakenews-net]

  spark:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./:/app
    networks: [fakenews-net]

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    depends_on: [spark]
    volumes:
      - ./:/app
    networks: [fakenews-net]

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      IN_DOCKER: "1"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/fakenews_dw
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__WEBSERVER__WORKERS: "2"
      AIRFLOW__WEBSERVER__WORKER_TIMEOUT: "120"
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "300"
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "60"
    mem_limit: 2g
    mem_reservation: 1g
    ports:
      - "8081:8080"
    volumes:
      - ./fakenewsdetector/airflow/dags:/opt/airflow/dags
      - ./fakenewsdetector:/opt/airflow/fakenewsdetector
    networks: [fakenews-net]

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    depends_on: [postgres]
    environment:
      SUPERSET_SECRET_KEY: "fakenews-maroc-secret-key-2025"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://admin:admin@postgres:5432/fakenews_dw"
    command: >
      bash -c "superset db upgrade &&
               superset fab create-admin --username admin --firstname Admin --lastname Admin --email admin@emsi.ma --password admin || true &&
               superset init &&
               superset run -h 0.0.0.0 -p 8088 --with-threads"
    networks: [fakenews-net]

networks:
  fakenews-net:
    driver: bridge

volumes:
  minio_data:
  pg_data: