FROM apache/superset:latest
USER root
RUN /app/.venv/bin/python -m ensurepip && \
    /app/.venv/bin/python -m pip install psycopg2-binary
COPY superset_config.py /app/pythonpath/superset_config.py
ENV SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
USER superset